### ISSUE TITLE
AddOn archivieren?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/gloebals#8]
@schuer?

**Comment by schuer** [comment]
Ist es sehr ähnlich wie Global Settings? Ich habe noch nie unter die Haube geschaut.

Abgesehen davon: Es scheint noch bei einigen Leuten im Einsatz zu sein, und wenn man ein Projekt bei GitHub archiviert, können keinen Issues mehr erfasst werden. Insofern würde ich persönlich lieber noch etwas abwarten und es offen lassen. Aber nur meine Meinung.

**Comment by skerbis** [comment]
ok
